# arm_1_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: arm_1_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# arm_2_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: arm_2_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# endpoint_bracket_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: endpoint_bracket_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# rod_1_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: rod_1_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# rod_2_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: rod_2_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# rod_3_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: rod_3_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# rod_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: rod_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# triangle_joint_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: triangle_joint
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# gripper_m_joint_controller:
#   type: effort_controllers/JointPositionController
#   joint: gripper_m_joint
#   pid: {p: 100.0, i: 0.01, d: 1.0}


left_gripper_joint_1_controller:
  type: effort_controllers/JointPositionController
  joint: left_gripper_joint_1
  pid: {p: 100.0, i: 0.01, d: 10.0}

# left_gripper_joint_2_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: left_gripper_joint_2
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# left_gripper_joint_4_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: left_gripper_joint_4
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# left_gripper_joint_6_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: left_gripper_joint_6
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# left_gripper_joint_7_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: left_gripper_joint_7
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# left_gripper_joint_5_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: left_gripper_joint_5
#   pid: {p: 100.0, i: 0.01, d: 10.0}

right_gripper_joint_1_controller:
  type: effort_controllers/JointPositionController
  joint: right_gripper_joint_1
  pid: {p: 100.0, i: 0.01, d: 10.0}

# right_gripper_joint_2_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: right_gripper_joint_2
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# right_gripper_joint_4_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: right_gripper_joint_4
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# right_gripper_joint_6_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: right_gripper_joint_6
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# right_gripper_joint_7_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: right_gripper_joint_7
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# right_gripper_joint_5_controller:
#   type: velocity_controllers/JointVelocityController
#   joint: right_gripper_joint_5
#   pid: {p: 100.0, i: 0.01, d: 10.0}